name: Leo
favicon: null
layout_spectrum: 0.5169498543255031
typography_spectrum: 0.6188914459198713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5707137256395072
  lightness: 0.05764787760563195
  saturation: 0.545138030545786
  rhythmicContrast: 0.8088950456585735
purpose: []
